apiVersion: v1
kind: Service
metadata:
  name: gerenciador-oficina-service
spec:
  type: LoadBalancer
  selector:
    app: gerenciador-oficina-core-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
